### ISSUE TITLE
Instrumento

### ISSUE THREAD

**Issue by YaderDavid** [YaderDavid/MelB_Front-End#1]
1. Cuando se cambia de Bodega a Aula, se quedan habilitados/visibles los campos de Bodega, Estante y Gaveta.
2. Cuando esta en modo no editable, se puede editar el ID.
3. Dilata mucho la actualización de datos en un instrumento, probablemente en mi caso sea por conexión a internet.
4.  Cuando se esta añadiendo un instrumento (como nuevo registro) considero que no debería aparecer el toggle para habilitar edición, ya que sólo se está añadiendo.
5. A la hora de visualizar los instrumentos ingresados, no aparecen automáticamente en el listado de Instrumentos.
6. Cuando se dirige hacia el detalle del instrumentos, asegurarse que el toggle esté desactivado para actualizar, el estado del toggle queda en el estado anterior, no importando cual sea. 
7. Al momento de visualizar el detalle de un instrumento, y posterior la habilitación de su editación, considero que se debería bloquear la opción de búsqueda, ya que está en el proceso de actualización. Porque de lo contrario perdería lo que está actualizando.
8. El mensaje de Actualización no es especifico, solo dice Aviso. 
Algo curioso, cuando actualice solo el ID dijo Aviso, ahorita modifique otros campos si dijo el mensaje de Actualización. Al actualizar primero ID + otros campos, sigue diciendo AVISO. 
9. Si se hace la actualización a un registro (ID por ejemplo), y me dirijo a la visualización de la tabla para ver ese cambio, no me lo muestra. Sin embargo, si modifico otros campos (ID No incluido) en la tabla no muestra los cambios, pero SI en el DIV Detalle_Instrumento.
10. Hay problemas con la actualización de un ID. No lo actualiza.

**Comment by Orivera04** [comment]
Con respecto al escenario 9) y 5) añadi un boton actualizar a la parte de arriba. En el caso de ingresar o actualizar. automaticamente no se van a mostrar los datos nuevos o actualizados. tendria que presionar el boton.

**Comment by Orivera04** [comment]
El 10) y el 3) Creo que es tu internet.

**Comment by Orivera04** [comment]
El resto ya esta listo favor revalidar.
