### ISSUE TITLE
Si, los estudiantes son de la juventud y se pelan los instrumentos valio gaver el sistema

### ISSUE THREAD

**Issue by Orivera04** [YaderDavid/MelB_Front-End#2]

**Comment by Orivera04** [comment]
La propuesta es añadir un campo a estado con extraviado o algo asi de tal manera que verifiquemos el dato al hacer las remisioens.

**Comment by YaderDavid** [comment]
Añadir campo en Instrumento de Estado, pero ya tiene uno creo, que sería Estado refiriendose al estado fisico del instrumento.
Seria ese, o uno nuevo?

![image](https://user-images.githubusercontent.com/33787527/39393432-59b2711c-4a82-11e8-93f2-e191575d6801.png)

**Comment by Orivera04** [comment]
Si , ese estado se modificara el combobox de la pagina para añadir extraviado o algo asi.

**Comment by Orivera04** [comment]
Se renombro la issue
