### ISSUE TITLE
No se puede continuar el flujo de actualización cuando se esta en el formulario de añadir Remision

### ISSUE THREAD

**Issue by Orivera04** [YaderDavid/MelB_Front-End#4]
![image](https://user-images.githubusercontent.com/21187152/39661526-157c3ef4-5010-11e8-88da-1d42027270de.png)

Si, presionamos el botón actualizar, saldrá el mensaje que sale en pantalla comentando que debemos activar el modo edición.

![image](https://user-images.githubusercontent.com/21187152/39661542-5ad73670-5010-11e8-84cc-a8ecc3953e12.png)

Pero no hay ningun modo de edición dado a que estamos en el modo de añadir. no en el de detalle.

**Comment by YaderDavid** [comment]
Con respecto a esto, pues lo habia dejado asi, ya que se deberia de editar en teoria cuando se visualizara el detalle, no cuando se esta añadiendo...
Porque el actualizar, recordemos que es solamente dado para la observacion final, y pues si se actualiza en ese momento estaria cerrando la remision, Y el boton actualizar, pues es porque es la misma tabla.

**Comment by YaderDavid** [comment]
Listo
